worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream graylog {
        server graylog1:9000;
        server graylog2:9000;
        server graylog3:9000;
    }

    server {
        listen 1514 ssl;  # Enable SSL
        server_name your_domain_or_IP;  # Change to your domain or IP

        ssl_certificate /etc/ssl/certs/your_cert.crt;  # Path to your SSL certificate
        ssl_certificate_key /etc/ssl/private/your_key.key;  # Path to your SSL private key

        location / {
            proxy_pass http://graylog;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
